services:
  backend:
    image: node:latest
    container_name: backend
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    networks:
      - transcendence_net
    env_file:
      - ./backend/config/.backend.env
  frontend:
    image: node:latest
    container_name: frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT:-5173}:${PORT:-5173}"
    networks:
      - transcendence_net
    env_file:
      - ./frontend/config/.frontend.env
    depends_on:
      - backend
    
networks:
  transcendence_net:
    driver: bridge
    