services:
  backend:
    image: node:latest
    container_name: backend
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    networks:
      - my_network
    env_file:
      - ./backend/config/.backend.env
    
networks:
  my_network:
    driver: bridge
    