services:
  backend:
    image: node:latest
    container_name: backend
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    networks:
      - my_network
    depends_on:
      - db
    env_file:
      - ./backend/config/.backend.env
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./backend/config/.db.env
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-mydb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/migrations:/docker-entrypoint-initdb.d
    
networks:
  my_network:
    driver: bridge
    