services:
  backend:
    image: node:latest
    container_name: backend
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    networks:
      - transcendence_net
    env_file:
      - ./backend/config/.backend.env
  frontend:
    image: node:latest
    container_name: frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "${PORT:-5173}:${PORT:-5173}"
    networks:
      - transcendence_net
    env_file:
      - ./frontend/config/.frontend.env
    depends_on:
      - backend

  elasticsearch:
    build: ./elk_stack/elasticsearch
    container_name: transcendence-elasticsearch
    ports: ["9200:9200", "9300:9300"]
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - transcendence_net
    restart: unless-stopped

  logstash:
    build: ./elk_stack/logstash
    container_name: transcendence-logstash
    ports: ["5000:5000", "5001:5001", "9600:9600"] # "5044:5044"
    volumes:
      - logstash-data:/usr/share/logstash/data
    depends_on:
      - elasticsearch
    networks:
      - transcendence_net
    restart: unless-stopped

  kibana:
    build: ./elk_stack/kibana
    container_name: transcendence-kibana
    ports: ["5601:5601"]
    depends_on:
      - elasticsearch
    networks:
      - transcendence_net
    restart: unless-stopped
    
networks:
  transcendence_net:
    driver: bridge
  
volumes:
  elasticsearch-data:
  logstash-data: